app/__init__.py
# from flask import Flask
from flask import Flask, request, jsonify, render_template
from .data_loader import load_data

def create_app():
    app = Flask(__name__, template_folder='../templates')
    
    from .routes.home import home_bp
    from .routes.artist import artist_bp
    from .routes.search import search_bp

    app.register_blueprint(home_bp)
    app.register_blueprint(artist_bp)
    app.register_blueprint(search_bp)

    return app

app/routes/artist.py
from flask import Blueprint, render_template, Flask
from flask import current_app

artist_bp = Blueprint('artist', __name__, template_folder='../templates')

@artist_bp.route("/artists")
def artist_list():
    artist_indices = current_app.config['artist_indices'] 
    return render_template("artists.html", artists=list(artist_indices.keys()))

@artist_bp.route("/artist/<artist_name>")
def artist_page(artist_name):
    data_list = current_app.config['data_list'] 
    artist_indices = current_app.config['artist_indices'] 
    if artist_name not in artist_indices:
        return "Artist not found!", 404
    indices = artist_indices[artist_name]
    song_name_list = [data_list[i]['song_name'] for i in indices]
    artist_data = list(zip(indices, song_name_list))

    return render_template("artist.html", artist=artist_name, artist_data=artist_data)

@artist_bp.route("/artist/<artist_name>/song/<song_name>/<idx>")
def song_page(artist_name, song_name, idx):
    data_list = current_app.config['data_list'] 
    knn_result = current_app.config['knn_result']
    idx = int(idx)
    data = data_list[idx]
    
    lyrics = data['lyrics'].replace('\n', '<br>')
    summary = data['summary_3'].replace('.', '<br>')

    knn_songs = []
    for i, max_sim, mean_sim, min_sim in knn_result[idx]:
        t_data = data_list[i]
        knn_songs.append([i, t_data['artist_name'], t_data['song_name'], t_data['summary_1'], max_sim])
    
    return render_template("song.html", 
               artist=artist_name, 
               song=song_name, 
               summary=summary, 
               lyrics=lyrics,
               knn_songs=knn_songs
                          )

app/routes/home.py
from flask import Blueprint, render_template

home_bp = Blueprint('home', __name__, template_folder='../templates')

@home_bp.route('/')
def home():
    return render_template('home.html')

app/routes/search.py
from app.utils.knn import knn_from_input_sentence, knn_result_to_html, knn_result_to_json
from flask import Blueprint, render_template, request, jsonify
from flask import current_app
from flask_cors import CORS

search_bp = Blueprint('search', __name__, template_folder='../templates')
CORS(search_bp)

@search_bp.route("/search", methods=["GET", "POST"])
def search_page():
    model = current_app.config['model']
    data_list = current_app.config['data_list']
    V1 = current_app.config['V1']
    V2 = current_app.config['V2']
    V3 = current_app.config['V3']
    Va = current_app.config['Va']

    print('search_page_load_start')

    result = ""
    user_input = ""
    if request.method == "POST":
        user_input = request.form["user_input"]
        result = knn_from_input_sentence(user_input, model, data_list, V1, V2, V3, Va)
        result = knn_result_to_html(result, data_list)

    return render_template("search.html", result=result, input_sentence=user_input)


@search_bp.route("/api/search", methods=["POST"])
def search_page_restapi():
    model = current_app.config['model']
    data_list = current_app.config['data_list']
    V1 = current_app.config['V1']
    V2 = current_app.config['V2']
    V3 = current_app.config['V3']
    Va = current_app.config['Va']

    print('search_page_restAPI_load_start')

    data = request.get_json()
    if not data or "user_input" not in data:
        return jsonify({
            "status": "fail",
            "message": "Missing 'user_input' in request body"
        }), 400

    user_input = data["user_input"]

    try:
        result = knn_from_input_sentence(user_input, model, data_list, V1, V2, V3, Va)
        result = knn_result_to_json(result, data_list)

        return jsonify({
            "status": "success",
            "data": result,
            "message": "추천 성공"
        }), 200

    except Exception as e:
        current_app.logger.error(f"추천 중 오류 발생: {e}")
        return jsonify({
            "status": "error",
            "message": "Internal server error"
        }), 500

main.py
from app import create_app
app = create_app()

# from app.utils.knn import knn_from_input_sentence, knn_result_to_html
with app.app_context():
    from app.utils.knn import knn_from_input_sentence, knn_result_to_html
    from app.data_loader import load_data
    load_data(app)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)

templates/artist.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body>
        <a href="/artists">전체 아티스트 페이지로 돌아가기</a>
        <h2>{{ artist }}의 곡 목록</h2>
        <ul>
        {% for i, song in artist_data %}
            <li><a href="{{ url_for('artist.song_page', artist_name=artist, song_name=song, idx=i) }}">{{ song }}</a></li>
        {% endfor %}
        </ul>
    </body>
</html>

templates/artists.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    </head>
    
    <body>
        <a href="/">메인 페이지로 돌아가기</a>
        <h1>전체 아티스트</h1>
        <ul>
            {% for artist in artists %}
                <li><a href="{{ url_for('artist.artist_page', artist_name=artist) }}">{{ artist }}</a></li>
            {% endfor %}
        </ul>
    </body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body>
        <h2>노래의 가사에 집중하면 보다 더 풍요로운 청취가 가능합니다.</h2>
        
        <a href="/search">직접 문장을 입력해서 비슷한 가사를 찾아볼래요</a><br>
        <a href="/artists">제가 좋아하는 아티스트와 가사가 비슷한 곡을 찾고싶어요</a>
    
    </body>
</html>

templates/search.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
        
        <style>
            body {
                margin: 0;
                padding: 20px; /* 필요하면 패딩만 주자 */
            }
        </style>
        
    </head>
    
    <body>
        <div class="prose">
            <h2 class="text-2xl font-semibold text-gray-800">
                입력한 문장과 최대한 비슷한 가사를 찾아볼게요!
            </h2>

            <div style="width: 100%;">
                <form method="post" style="width: 100%; max-width: 800px;">
                    <textarea name="user_input" placeholder="(예시) 다시는 돌아오지 않을 젊음을 헛되이 낭비하지 말고 뜨겁게 살자"
                        style="width: 100%; height: 150px; padding: 16px; border: 1px solid #ccc; border-radius: 8px; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1); resize: vertical; font-size: 16px; box-sizing: border-box;"></textarea>
                    <button type="submit" style="margin-top: 12px; padding: 10px 20px; background-color: #3b82f6; color: white; border: none; border-radius: 6px; font-size: 16px; cursor: pointer;">
                        Search
                    </button>
                </form>
            </div>


            <p>
                입력 문장 : {{ input_sentence | safe }} <br>
            </p>


            <p>{{ result | safe }}</p>


            <a href="/" class="underline text-blue-600 hover:text-blue-800 visited:text-purple-600"> 메인 페이지 </a>

        </div>
    </body>
</html>

templates/song.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body>
        <a href="{{ url_for('artist.artist_page', artist_name=artist) }}">{{ artist }} 페이지로 돌아가기</a>
    
        <h1>{{ artist }} - {{ song }}</h1>

        <h2> 가사 요약 </h2>
        <div style="background-color: #f0f0f0; color: #555555; padding: 10px; border-radius: 5px;">
          <p>{{ summary | safe }}</p>
        </div>

        <h2> 전체 가사 </h2>
        <div style="background-color: #f0f0f0; color: #555555; padding: 10px; border-radius: 5px;">
          <p>{{ lyrics | safe }}</p>
        </div>

        <h2> 유사한 가사의 다른 곡 </h2>

        {% for t_i, t_artist_name, t_song_name, t_summary, sim in knn_songs %}
            <a href="{{ url_for('artist.song_page', artist_name=t_artist_name, song_name=t_song_name, idx=t_i) }}">{{ t_artist_name }} - {{ t_song_name }}</a><br>
            <p>{{ t_summary }}</p>
            <p>유사도 : {{ sim }}</p>
            <br>
            
        {% endfor %}

    </body>
</html>